// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Papasur.Infrastructure.Persistence;

#nullable disable

namespace Papasur.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Papasur.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entry");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_entry_action");

                    b.HasIndex("ActorRole")
                        .HasDatabaseName("ix_audit_entry_actor_role");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entry_occurred_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_entry_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entry_entity_type_entity_id");

                    b.ToTable("audit_entry", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.CampoPlantilla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("etiqueta");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatorio");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PlantillaDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plantilla_documento_id");

                    b.Property<string>("ReglaMapeo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("regla_mapeo");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_dato");

                    b.HasKey("Id")
                        .HasName("pk_campo_plantilla");

                    b.HasIndex("PlantillaDocumentoId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_campo_plantilla_plantilla_documento_id_clave");

                    b.ToTable("campo_plantilla", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.DocumentoExportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<Guid?>("MovimientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimiento_id");

                    b.Property<Guid>("PlantillaDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plantilla_documento_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("VersionPlantilla")
                        .HasColumnType("integer")
                        .HasColumnName("version_plantilla");

                    b.HasKey("Id")
                        .HasName("pk_documento_exportacion");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_documento_exportacion_created_by_user_id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_documento_exportacion_lote_id");

                    b.HasIndex("MovimientoId")
                        .HasDatabaseName("ix_documento_exportacion_movimiento_id");

                    b.HasIndex("PlantillaDocumentoId")
                        .HasDatabaseName("ix_documento_exportacion_plantilla_documento_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_documento_exportacion_status_id");

                    b.ToTable("documento_exportacion", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.PlantillaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Organismo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("organismo");

                    b.Property<string>("PaisDestino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais_destino");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_plantilla_documento");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_plantilla_documento_tipo");

                    b.HasIndex("Nombre", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_plantilla_documento_nombre_version");

                    b.ToTable("plantilla_documento", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.ValorCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampoPlantillaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campo_plantilla_id");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmado");

                    b.Property<Guid>("DocumentoExportacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_exportacion_id");

                    b.Property<string>("InferidoDesde")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("inferido_desde");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<string>("Valor")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_valor_campo");

                    b.HasIndex("CampoPlantillaId")
                        .HasDatabaseName("ix_valor_campo_campo_plantilla_id");

                    b.HasIndex("DocumentoExportacionId", "CampoPlantillaId")
                        .IsUnique()
                        .HasDatabaseName("ix_valor_campo_documento_exportacion_id_campo_plantilla_id");

                    b.ToTable("valor_campo", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_item");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_item_nombre");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Statuses.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_status");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_status_code");

                    b.ToTable("status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en_proceso",
                            Name = "En proceso"
                        },
                        new
                        {
                            Id = 2,
                            Code = "finalizado",
                            Name = "Finalizado"
                        },
                        new
                        {
                            Id = 3,
                            Code = "cancelado",
                            Name = "Cancelado"
                        });
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Campo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuadrante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cuadrante");

                    b.Property<string>("Establecimiento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("establecimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pivote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pivote");

                    b.HasKey("Id")
                        .HasName("pk_campo");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_campo_nombre");

                    b.ToTable("campo", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_cliente_nombre");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampoId")
                        .HasColumnType("uuid")
                        .HasColumnName("campo_id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("SuperficieHa")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("superficie_ha");

                    b.Property<Guid>("VariedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("variedad_id");

                    b.HasKey("Id")
                        .HasName("pk_lote");

                    b.HasIndex("CampoId")
                        .HasDatabaseName("ix_lote_campo_id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("ix_lote_codigo");

                    b.HasIndex("VariedadId")
                        .HasDatabaseName("ix_lote_variedad_id");

                    b.ToTable("lote", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Bolsas")
                        .HasColumnType("integer")
                        .HasColumnName("bolsas");

                    b.Property<string>("Calibre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calibre");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comisionista")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("comisionista");

                    b.Property<string>("Destino")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("destino");

                    b.Property<string>("Dtv")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dtv");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("KgPromedio")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("kg_promedio");

                    b.Property<decimal>("Kilogramos")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("kilogramos");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<string>("NumeroRemito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_remito");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Presentacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("presentacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TransportistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("transportista_id");

                    b.HasKey("Id")
                        .HasName("pk_movimiento");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_movimiento_cliente_id");

                    b.HasIndex("Dtv")
                        .HasDatabaseName("ix_movimiento_dtv");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_movimiento_fecha");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_movimiento_lote_id");

                    b.HasIndex("NumeroRemito")
                        .HasDatabaseName("ix_movimiento_numero_remito");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_movimiento_tipo");

                    b.HasIndex("TransportistaId")
                        .HasDatabaseName("ix_movimiento_transportista_id");

                    b.ToTable("movimiento", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Transportista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_transportista");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_transportista_nombre");

                    b.ToTable("transportista", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Variedad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_variedad");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_variedad_nombre");

                    b.ToTable("variedad", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Users.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_token_user_id");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso total al sistema.",
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Supervisa y consulta la operación.",
                            Name = "supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Opera la documentación día a día.",
                            Name = "agent"
                        });
                });

            modelBuilder.Entity("Papasur.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_employee_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_user_status");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Papasur.Domain.Audit.AuditEntry", b =>
                {
                    b.HasOne("Papasur.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_entry_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.CampoPlantilla", b =>
                {
                    b.HasOne("Papasur.Domain.Documentos.PlantillaDocumento", "PlantillaDocumento")
                        .WithMany("Campos")
                        .HasForeignKey("PlantillaDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campo_plantilla_plantilla_documento_plantilla_documento_id");

                    b.Navigation("PlantillaDocumento");
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.DocumentoExportacion", b =>
                {
                    b.HasOne("Papasur.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documento_exportacion_user_created_by_user_id");

                    b.HasOne("Papasur.Domain.Trazabilidad.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documento_exportacion_lote_lote_id");

                    b.HasOne("Papasur.Domain.Trazabilidad.Movimiento", "Movimiento")
                        .WithMany("Documentos")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documento_exportacion_movimiento_movimiento_id");

                    b.HasOne("Papasur.Domain.Documentos.PlantillaDocumento", "PlantillaDocumento")
                        .WithMany()
                        .HasForeignKey("PlantillaDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documento_exportacion_plantilla_documento_plantilla_documen");

                    b.HasOne("Papasur.Domain.Statuses.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documento_exportacion_status_status_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lote");

                    b.Navigation("Movimiento");

                    b.Navigation("PlantillaDocumento");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.ValorCampo", b =>
                {
                    b.HasOne("Papasur.Domain.Documentos.CampoPlantilla", "CampoPlantilla")
                        .WithMany()
                        .HasForeignKey("CampoPlantillaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_valor_campo_campo_plantilla_campo_plantilla_id");

                    b.HasOne("Papasur.Domain.Documentos.DocumentoExportacion", "DocumentoExportacion")
                        .WithMany("Valores")
                        .HasForeignKey("DocumentoExportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_valor_campo_documento_exportacion_documento_exportacion_id");

                    b.Navigation("CampoPlantilla");

                    b.Navigation("DocumentoExportacion");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Lote", b =>
                {
                    b.HasOne("Papasur.Domain.Trazabilidad.Campo", "Campo")
                        .WithMany("Lotes")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lote_campo_campo_id");

                    b.HasOne("Papasur.Domain.Trazabilidad.Variedad", "Variedad")
                        .WithMany("Lotes")
                        .HasForeignKey("VariedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lote_variedad_variedad_id");

                    b.Navigation("Campo");

                    b.Navigation("Variedad");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Movimiento", b =>
                {
                    b.HasOne("Papasur.Domain.Trazabilidad.Cliente", "Cliente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimiento_cliente_cliente_id");

                    b.HasOne("Papasur.Domain.Trazabilidad.Lote", "Lote")
                        .WithMany("Movimientos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_lote_lote_id");

                    b.HasOne("Papasur.Domain.Trazabilidad.Transportista", "Transportista")
                        .WithMany("Movimientos")
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimiento_transportista_transportista_id");

                    b.Navigation("Cliente");

                    b.Navigation("Lote");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("Papasur.Domain.Users.PasswordResetToken", b =>
                {
                    b.HasOne("Papasur.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papasur.Domain.Users.User", b =>
                {
                    b.HasOne("Papasur.Domain.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.DocumentoExportacion", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("Papasur.Domain.Documentos.PlantillaDocumento", b =>
                {
                    b.Navigation("Campos");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Campo", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Cliente", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Lote", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Movimiento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Transportista", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Papasur.Domain.Trazabilidad.Variedad", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Papasur.Domain.Users.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
